import pandas as pd
import json

# =========================================================
# 1. LOAD THE PIPELINE DATA
# =========================================================
print("Loading AI Predictions and Network Edges...")
gnn_preds = pd.read_csv('gnn_predictions.csv', index_col=0)
A_matrix = pd.read_csv('edge_matrix_A.csv', index_col=0)

# The final weights generated by your PyPortfolioOpt Agent
agent_weights = {
    "AAPL": 0.0, "MSFT": 0.0, "NVDA": 0.0,
    "BAC": 0.0, "GS": 0.0, "JPM": 0.0,
    "COP": 30.07, "CVX": 0.0, "XOM": 69.93
}

# =========================================================
# 2. BUILD THE GRAPH JSON STRUCTURE
# =========================================================
nodes = []
for ticker, row in gnn_preds.iterrows():
    nodes.append({
        "id": ticker,
        "sector": row["Sector"],
        "risk": round(row["Contagion_Risk"], 4),
        "weight": agent_weights.get(ticker, 0.0)
    })

links = []
# Iterate through the adjacency matrix to find active edges
for i in A_matrix.index:
    for j in A_matrix.columns:
        val = A_matrix.loc[i, j]
        # Only add the edge if a connection exists
        if pd.notna(val) and val > 0:
            links.append({"source": i, "target": j, "value": round(val, 3)})

graph_data = {"nodes": nodes, "links": links}
graph_json = json.dumps(graph_data)

# =========================================================
# 3. INJECT INTO D3.JS HTML TEMPLATE
# =========================================================
html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GNN Contagion & Agent Reallocation</title>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #0f172a; color: white; margin: 0; overflow: hidden; }}
        #ui-container {{ position: absolute; top: 20px; left: 20px; background: rgba(30, 41, 59, 0.8); padding: 15px; border-radius: 8px; border: 1px solid #334155; }}
        button {{ display: block; width: 100%; margin-bottom: 10px; padding: 10px; background-color: #3b82f6; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; }}
        button:hover {{ background-color: #2563eb; }}
        .tooltip {{ position: absolute; text-align: left; padding: 10px; font-size: 12px; background: #1e293b; border: 1px solid #475569; border-radius: 4px; pointer-events: none; opacity: 0; color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }}
    </style>
</head>
<body>

<div id="ui-container">
    <h3 style="margin-top: 0;">View Mode</h3>
    <button onclick="setMode('sector')">1. Sector Clustering</button>
    <button onclick="setMode('risk')">2. Contagion Risk Heatmap</button>
    <button onclick="setMode('agent')">3. Agent Allocation</button>
</div>

<div id="graph"></div>
<div class="tooltip" id="tooltip"></div>

<script>
    const data = {graph_json};
    const width = window.innerWidth;
    const height = window.innerHeight;

    const svg = d3.select("#graph").append("svg")
        .attr("width", width)
        .attr("height", height);

    const tooltip = d3.select("#tooltip");

    // Initialize Force Simulation
    const simulation = d3.forceSimulation(data.nodes)
        .force("link", d3.forceLink(data.links).id(d => d.id).distance(150))
        .force("charge", d3.forceManyBody().strength(-800))
        .force("center", d3.forceCenter(width / 2, height / 2))
        .force("collide", d3.forceCollide().radius(40));

    // Draw Edges
    const link = svg.append("g")
        .selectAll("line")
        .data(data.links)
        .enter().append("line")
        .attr("stroke", "#475569")
        .attr("stroke-opacity", 0.6)
        .attr("stroke-width", d => d.value * 5); // Thicker line = higher correlation

    // Draw Nodes
    const node = svg.append("g")
        .selectAll("circle")
        .data(data.nodes)
        .enter().append("circle")
        .attr("r", 25)
        .attr("stroke", "#fff")
        .attr("stroke-width", 1.5)
        .call(d3.drag()
            .on("start", dragstarted)
            .on("drag", dragged)
            .on("end", dragended));

    // Add Labels
    const labels = svg.append("g")
        .selectAll("text")
        .data(data.nodes)
        .enter().append("text")
        .attr("dy", 4)
        .attr("text-anchor", "middle")
        .style("font-size", "12px")
        .style("font-weight", "bold")
        .style("fill", "white")
        .style("pointer-events", "none")
        .text(d => d.id);

    // Tooltip Interactions
    node.on("mouseover", function(event, d) {{
        tooltip.transition().duration(200).style("opacity", .9);
        tooltip.html(`
            <strong>${{d.id}}</strong><br/>
            Sector: ${{d.sector}}<br/>
            Contagion Risk: ${(d.risk * 100).toFixed(1)}%<br/>
            Portfolio Weight: ${{d.weight}}%
        `)
        .style("left", (event.pageX + 15) + "px")
        .style("top", (event.pageY - 28) + "px");
    }})
    .on("mouseout", function(d) {{
        tooltip.transition().duration(500).style("opacity", 0);
    }});

    // Simulation Tick Update
    simulation.on("tick", () => {{
        link.attr("x1", d => d.source.x)
            .attr("y1", d => d.source.y)
            .attr("x2", d => d.target.x)
            .attr("y2", d => d.target.y);
        node.attr("cx", d => d.x).attr("cy", d => d.y);
        labels.attr("x", d => d.x).attr("y", d => d.y);
    }});

    // Drag Functions
    function dragstarted(event, d) {{
        if (!event.active) simulation.alphaTarget(0.3).restart();
        d.fx = d.x; d.fy = d.y;
    }}
    function dragged(event, d) {{ d.fx = event.x; d.fy = event.y; }}
    function dragended(event, d) {{
        if (!event.active) simulation.alphaTarget(0);
        d.fx = null; d.fy = null;
    }}

    // Color Logic for View Modes
    const sectorColors = d3.scaleOrdinal(d3.schemeCategory10);
    const riskColor = d3.scaleSequential(d3.interpolateReds).domain([0, 1]);

    window.setMode = function(mode) {{
        node.transition().duration(750).style("fill", d => {{
            if (mode === 'sector') return sectorColors(d.sector);
            if (mode === 'risk') return riskColor(d.risk);
            if (mode === 'agent') return d.weight > 0 ? "#10b981" : "#334155"; // Green if invested, dark gray if dumped
        }});
    }};

    // Initialize default mode
    setMode('sector');
</script>
</body>
</html>
"""

# Write the final HTML file
with open('dashboard.html', 'w') as f:
    f.write(html_template)

print("Success! 'dashboard.html' has been generated in your project folder.")