import pandas as pd
import numpy as np
from pypfopt import black_litterman, risk_models, expected_returns
from pypfopt.efficient_frontier import EfficientFrontier

# =========================================================
# 1. LOAD DATA & AI PREDICTIONS
# =========================================================
print("Loading Historical Returns and GNN Predictions...")
daily_returns = pd.read_csv('daily_returns.csv', index_col=0, parse_dates=True)

# FIX 1: Drop the first row which contains NaN values from pct_change()
daily_returns = daily_returns.dropna()

gnn_preds = pd.read_csv('gnn_predictions.csv', index_col=0)

# We need the market capitalization to calculate baseline market weights.
# For this simulation, we will assume all 9 stocks have an equal market cap.
market_caps = {ticker: 1000000000 for ticker in daily_returns.columns}

# =========================================================
# 2. CALCULATE BASELINE MARKET PRIORS
# =========================================================
# FIX 1: Explicitly tell the function we are passing returns, not prices!
S = risk_models.sample_cov(daily_returns, returns_data=True)

# FIX 2: Use the academic standard market risk aversion constant (2.5) 
# instead of trying to calculate it from 9 individual stocks.
delta = 2.5
market_prior = black_litterman.market_implied_prior_returns(market_caps, delta, S)

print("\nBaseline Market Expected Returns (Pre-Crash):")
print(market_prior.round(4))

# =========================================================
# 3. TRANSLATE AI SIGNAL TO FINANCIAL VIEWS
# =========================================================
print("\nTranslating GNN Signals into Agent Views...")
agent_views = {}
for ticker, row in gnn_preds.iterrows():
    risk = row['Contagion_Risk']
    # Formula mapping 0->0.10, and 1->-0.20
    expected_return = 0.10 - (risk * 0.30) 
    agent_views[ticker] = expected_return

print("Programmatic Views generated by the Agent:")
for ticker, view in agent_views.items():
    print(f"{ticker}: {view*100:.2f}%")

# =========================================================
# 4. BLACK-LITTERMAN OPTIMIZATION
# =========================================================
# Combine the market prior with our AI's absolute views
bl = black_litterman.BlackLittermanModel(S, pi=market_prior, absolute_views=agent_views)

# Calculate the new, blended expected returns and covariance matrix
bl_returns = bl.bl_returns()
bl_cov = bl.bl_cov()

# =========================================================
# 5. EXECUTE THE DEFENSIVE PORTFOLIO REBALANCING
# =========================================================
print("\nCalculating Optimal Defensive Weights...")
ef = EfficientFrontier(bl_returns, bl_cov)

# FIX 2: Pass the stabilization lambda function positionally
ef.add_objective(lambda w: 0) 

weights = ef.max_sharpe()

# Clean up the output (removes near-zero weights)
cleaned_weights = ef.clean_weights()

print("\n=======================================================")
print("FINAL AGENT PORTFOLIO ALLOCATION:")
print("=======================================================")
for ticker, weight in cleaned_weights.items():
    print(f"{ticker}: {weight*100:.2f}%")

# Display expected portfolio performance
print("\nExpected Portfolio Performance Post-Rebalance:")
ef.portfolio_performance(verbose=True)